on: [push]

jobs:
  send-email:
    runs-on: ubuntu-latest
    name: Test Send email
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: 'v1.1'
      - name: "Send email"
        id: "emailsent"
        uses: raviswam-digib/test-GH-actions@v4.1
        #  with:
        #    send-email-to: 'ravi.swaminathan@jpmchase.com'
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "This time was ${{ steps.emailsent.outputs.time }}"
