on: [push]

jobs:
  send-email:
    runs-on: ubuntu-latest
    name: Test Send email
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: 'Send email'
        run: |
          apt-get install mailutils
          chmod +x ./public/test.sh
          ./public/test.sh
        shell: bash
