on: [push]

jobs:
  send-email:
    runs-on: ubuntu-latest
    name: Test Send email
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: 'Send email'
        run: |
          chmod +x ./public/test.sh
          ./public/test.sh
        shell: bash
      - name: 'Send js email'
        id:    'sendemail'
        uses: raviswam-digib/test-GH-actions@v10.1
        with:
          email: 'ravi.swaminathan@jpmchasep.com'
          emailmsg: ' Hello!!! Ravi'
      - name: Get the output time
        run: echo "The time was ${{ steps.sendemail.outputs.time }}"
